# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vb1fit <- function(alpha, params, prior, data, options) {
    .Call('_vbsrm_vb1fit', PACKAGE = 'vbsrm', alpha, params, prior, data, options)
}

vb2fit <- function(alpha, prior, data, options) {
    .Call('_vbsrm_vb2fit', PACKAGE = 'vbsrm', alpha, prior, data, options)
}

